title = "TOML Example"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = 1
loadpretrainedmodel = true
pretrainedmodelpath = "epoch10.pt"
savemodel = true
modelsavepath = "savedmodel.pt"

[input]
batchsize = 12
numworkers = 12
shuffle = true

[model]
type = "LSTM"
inputdim = 256
hiddendim = 256
numclasses = 500
numlstms = 2


[training]
train = true
epochs = 12
startepoch = 10
statsfrequency = 1000
dataset = "/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4"

[validation]
validate = true
dataset = "/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4"
saveaccuracy = true
accuracyfilelocation = "accuracy.txt"
