title = "TOML Example"

[general]
usecudnn = true
usecudnnbenchmark = true
usemultigpu = false
gpuids = [1, 2]
loadsaved = false

[input]
batchsize = 12
numworkers = 12
shuffle = true

[model]
type = "LSTM-init"
inputdim = 256
hiddendim = 256
numclasses = 500
numlstms = 2


[training]
train = true
validate = true
epochs = 10
startepoch = 7
statsfrequency = 1000
